/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The process is up */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The API can serve requests (its database answers) */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find symbols by ticker prefix or name */
        get: operations["searchSymbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols/{ticker}/candles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Daily candles, adjusted for splits (and dividends) on request */
        get: operations["getDailyCandles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem_Output: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance: string;
            /** Format: date-time */
            timestamp: string;
            errors?: {
                path: (string | number)[];
                message: string;
            }[];
        };
        HealthStatus_Output: {
            /** @constant */
            status: "ok";
        };
        SymbolSummary_Output: {
            ticker: string;
            name: string;
            exchange: string;
            latestClose: components["schemas"]["LatestClose_Output"] | null;
        };
        LatestClose_Output: {
            /** Format: date */
            date: string;
            close: string;
            previousClose: string | null;
        };
        SymbolList_Output: {
            symbols: components["schemas"]["SymbolSummary_Output"][];
        };
        /** @enum {string} */
        Adjustment_Output: "raw" | "split" | "all";
        Candle_Output: {
            /** Format: date */
            time: string;
            open: string;
            high: string;
            low: string;
            close: string;
            volume: string;
        };
        Split_Output: {
            /** Format: date */
            exDate: string;
            from: string;
            to: string;
        };
        CandleSeries_Output: {
            ticker: string;
            adjustment: components["schemas"]["Adjustment_Output"];
            candles: components["schemas"]["Candle_Output"][];
            splits: components["schemas"]["Split_Output"][];
        };
        /** @enum {string} */
        Adjustment: "raw" | "split" | "all";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus_Output"];
                };
            };
            /** @description Any error, as an RFC 9457 problem detail */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem_Output"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus_Output"];
                };
            };
            /** @description Any error, as an RFC 9457 problem detail */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem_Output"];
                };
            };
        };
    };
    searchSymbols: {
        parameters: {
            query?: {
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolList_Output"];
                };
            };
            /** @description Any error, as an RFC 9457 problem detail */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem_Output"];
                };
            };
        };
    };
    getDailyCandles: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                adjustment?: components["schemas"]["Adjustment"];
            };
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandleSeries_Output"];
                };
            };
            /** @description Any error, as an RFC 9457 problem detail */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem_Output"];
                };
            };
        };
    };
}
