/**
 * Serializes resolved themes to the three committed outputs: token CSS, a
 * W3C DTCG `tokens.json` for other tools (Figma, Style Dictionary), and a
 * slim runtime registry so apps don't bundle the theme sources.
 */

import {
  COLOR_TOKENS,
  LEGACY_ALIASES,
  MODES,
  SHARED_TOKENS,
  type Mode,
  type ResolvedTheme,
} from "./schema";

const HEADER =
  "Generated by packages/ui/scripts/build-tokens.ts from src/tokens/themes. " +
  "Do not edit; run `pnpm --filter @astraq/ui tokens`.";

const declarations = (entries: [string, string][], indent = "  ") =>
  entries.map(([name, value]) => `${indent}--ds-${name}: ${value};`).join("\n");

/**
 * Selectors per theme and mode. The first theme is also the fallback when
 * `data-theme` is absent, and dark is the fallback when `data-mode` is.
 */
function selectors(theme: string, mode: Mode, isDefault: boolean) {
  const own =
    mode === "dark"
      ? `:root[data-theme="${theme}"]:not([data-mode="light"])`
      : `:root[data-theme="${theme}"][data-mode="light"]`;
  if (!isDefault) return own;
  return `${mode === "dark" ? ":root" : ':root[data-mode="light"]'},\n${own}`;
}

export function emitCss(themes: readonly ResolvedTheme[]): string {
  const blocks = themes.flatMap((theme, index) =>
    MODES.map((mode) => {
      const { tokens } = theme.modes[mode];
      const label = `${theme.source.label} · ${mode}${index === 0 ? " (default)" : ""}`;
      return `/* ${label} */\n${selectors(theme.source.name, mode, index === 0)} {\n  color-scheme: ${mode};\n${declarations(Object.entries(tokens))}\n}`;
    }),
  );

  const motion = Object.keys(SHARED_TOKENS)
    .filter((name) => name.startsWith("motion-"))
    .map((name): [string, string] => [name, "0ms"]);

  return `/* ${HEADER} */

:root {
${declarations(Object.entries(SHARED_TOKENS))}
}

@media (prefers-reduced-motion: reduce) {
  :root {
${declarations(motion, "    ")}
  }
}

${blocks.join("\n\n")}

/* Pre-PR 2 names for apps/web. Remove in PR 7. */
:root {
${Object.entries(LEGACY_ALIASES)
  .map(([legacy, token]) => `  --ds-${legacy}: var(--ds-${token});`)
  .join("\n")}
}
`;
}

export function emitJson(themes: readonly ResolvedTheme[]): string {
  const color = (value: string) => ({ $type: "color", $value: value });
  const ramp = (colors: readonly string[]) =>
    Object.fromEntries(colors.map((value, i) => [String(i + 1), color(value)]));

  const document = {
    $description: HEADER,
    ...Object.fromEntries(
      themes.map((theme) => [
        theme.source.name,
        {
          $description: theme.source.description,
          ...Object.fromEntries(
            MODES.map((mode) => {
              const { tokens, primitives } = theme.modes[mode];
              return [
                mode,
                {
                  primitive: {
                    neutral: ramp(primitives.neutral),
                    brand: ramp(primitives.brand),
                  },
                  color: Object.fromEntries(
                    COLOR_TOKENS.map((name) => [name, color(tokens[name])]),
                  ),
                },
              ];
            }),
          ),
        },
      ]),
    ),
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

export function emitRegistry(themes: readonly ResolvedTheme[]): string {
  const entries = themes
    .map(({ source }) =>
      [
        "  {",
        `    name: ${JSON.stringify(source.name)},`,
        `    label: ${JSON.stringify(source.label)},`,
        `    description: ${JSON.stringify(source.description)},`,
        "  },",
      ].join("\n"),
    )
    .join("\n");

  return `// ${HEADER}

export const THEMES = [
${entries}
] as const;

export const DEFAULT_THEME = ${JSON.stringify(themes[0].source.name)};
`;
}
