/**
 * Serializes resolved themes to the three committed outputs: token CSS, a
 * W3C DTCG `tokens.json` for other tools (Figma, Style Dictionary), and a
 * slim runtime registry so apps don't bundle the theme sources.
 */

import {
  COLOR_TOKENS,
  DENSITIES,
  DENSITY_VALUES,
  MODES,
  SHARED_TOKENS,
  THEME_TOKENS,
  type Mode,
  type ResolvedTheme,
} from "./schema";

const HEADER =
  "Generated by packages/ui/scripts/build-tokens.ts from src/tokens/themes. " +
  "Do not edit; run `pnpm --filter @astraq/ui tokens`.";

const declarations = (entries: [string, string][], indent = "  ") =>
  entries.map(([name, value]) => `${indent}--ds-${name}: ${value};`).join("\n");

const block = (comment: string, selector: string, body: string) =>
  `/* ${comment} */\n${selector} {\n${body}\n}`;

/**
 * Selectors per theme and mode. They match any element, not just `:root`, so
 * a subtree can carry its own `data-theme` / `data-mode` (Storybook's theme
 * matrix does). The first theme is also the fallback when `data-theme` is
 * absent, and dark is the fallback when `data-mode` is.
 */
function modeSelectors(theme: string, mode: Mode, isDefault: boolean) {
  const own =
    mode === "dark"
      ? `[data-theme="${theme}"]:not([data-mode="light"])`
      : `[data-theme="${theme}"][data-mode="light"]`;
  if (!isDefault) return own;
  return `${mode === "dark" ? ":root" : '[data-mode="light"]'},\n${own}`;
}

function themeSelectors(theme: string, isDefault: boolean) {
  return isDefault ? `:root,\n[data-theme="${theme}"]` : `[data-theme="${theme}"]`;
}

export function emitCss(themes: readonly ResolvedTheme[]): string {
  const themeBlocks = themes.map((theme, index) => {
    const { name, label, density } = theme.source;
    const entries: [string, string][] = [
      ...THEME_TOKENS.map((token): [string, string] => [token, theme.tokens[token]]),
      ...Object.entries(DENSITY_VALUES[density]),
    ];
    return block(
      `${label}${index === 0 ? " (default)" : ""}: type, shape, surfaces, ${density} density`,
      themeSelectors(name, index === 0),
      declarations(entries),
    );
  });

  // After the theme blocks, at the same specificity: an explicit
  // `data-density` beats the theme's default.
  const densityBlocks = DENSITIES.map((density) =>
    block(
      `${density} density`,
      `[data-density="${density}"]`,
      declarations(Object.entries(DENSITY_VALUES[density])),
    ),
  );

  const modeBlocks = themes.flatMap((theme, index) =>
    MODES.map((mode) =>
      block(
        `${theme.source.label} · ${mode}${index === 0 ? " (default)" : ""}`,
        modeSelectors(theme.source.name, mode, index === 0),
        `  color-scheme: ${mode};\n${declarations(Object.entries(theme.modes[mode].tokens))}`,
      ),
    ),
  );

  const motion = Object.keys(SHARED_TOKENS)
    .filter((name) => name.startsWith("motion-"))
    .map((name): [string, string] => [name, "0ms"]);

  return `/* ${HEADER} */

:root {
${declarations(Object.entries(SHARED_TOKENS))}
}

@media (prefers-reduced-motion: reduce) {
  :root {
${declarations(motion, "    ")}
  }
}

${themeBlocks.join("\n\n")}

${densityBlocks.join("\n\n")}

${modeBlocks.join("\n\n")}
`;
}

const DIMENSION_TOKENS = [
  "radius-sm",
  "radius-md",
  "radius-lg",
  "radius-xl",
  "radius-pill",
  "border-width",
  "focus-width",
] as const;

export function emitJson(themes: readonly ResolvedTheme[]): string {
  const color = (value: string) => ({ $type: "color", $value: value });
  const ramp = (colors: readonly string[]) =>
    Object.fromEntries(colors.map((value, i) => [String(i + 1), color(value)]));

  const document = {
    $description: HEADER,
    ...Object.fromEntries(
      themes.map((theme) => [
        theme.source.name,
        {
          $description: theme.source.description,
          font: Object.fromEntries(
            (["sans", "display", "mono"] as const).map((role) => [
              role,
              { $type: "fontFamily", $value: theme.tokens[`font-${role}`] },
            ]),
          ),
          dimension: Object.fromEntries(
            DIMENSION_TOKENS.map((name) => [
              name,
              { $type: "dimension", $value: theme.tokens[name] },
            ]),
          ),
          ...Object.fromEntries(
            MODES.map((mode) => {
              const { tokens, primitives } = theme.modes[mode];
              return [
                mode,
                {
                  primitive: {
                    neutral: ramp(primitives.neutral),
                    brand: ramp(primitives.brand),
                  },
                  color: Object.fromEntries(
                    COLOR_TOKENS.map((name) => [name, color(tokens[name])]),
                  ),
                },
              ];
            }),
          ),
        },
      ]),
    ),
  };
  return `${JSON.stringify(document, null, 2)}\n`;
}

export function emitRegistry(themes: readonly ResolvedTheme[]): string {
  const entries = themes
    .map(({ source }) =>
      [
        "  {",
        `    name: ${JSON.stringify(source.name)},`,
        `    label: ${JSON.stringify(source.label)},`,
        `    description: ${JSON.stringify(source.description)},`,
        `    density: ${JSON.stringify(source.density)},`,
        "  },",
      ].join("\n"),
    )
    .join("\n");

  return `// ${HEADER}

export const THEMES = [
${entries}
] as const;

export const DEFAULT_THEME = ${JSON.stringify(themes[0].source.name)};
`;
}
