export {
  Table,
  TableCaption,
  TableSortButton,
  TableWrap,
  Tbody,
  Td,
  Tfoot,
  Th,
  Thead,
  Tr,
  type TableAlign,
  type TableProps,
  type TableSortButtonProps,
  type TableWrapProps,
  type TdProps,
  type ThProps,
  type TrProps,
} from "./table";
